### ISSUE TITLE
Smart Fan I2C newer version missing control

### ISSUE THREAD

**Issue by DrJeff** [SequentMicrosystems/SmartFan-rpi#7]
No temp? 
```
 fan 0 trd
Not available for this hardware version
```
No LED?

```
fan 0 brd
Not available for this hardware version
```
NO Fan safety Temp?
```
fan 0 strd
Not available for this hardware version
```
Whaere are all the features of the fan? It doesn't even do the things the software has listed. Am i missing something?

**Comment by alexburcea2877** [comment]
Hi,

The option was available for the first version of the smart fan which has a microcontroller on it.
Anyway you need the temperature of the raspberry to control the fan.

**Comment by DrJeff** [comment]
I assume those are not available anymore, maybe change your software and description of the product that is deceiving it even says it has the microcontroller on it on the store.

**Comment by alexburcea2877** [comment]
Yes, these features are not available on the current version but we need to keep the retro compatibility.
We do the current version of the smart fan without the CPU because was not available (chip shortages).
We plan the next version will be with microcontroller but we still have in stock the one without CPU.
